# This yml file builds a mysql and a tomcat container
version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/mysql.conf.d/
    ports:
      - "6033:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
  tomcat:
    container_name: tomcat
    restart: always
    image: tomcat
    ports:
      - 8080:8080
      - 8009:8009
    links:
      -mysql:m1 #Connect to database mirroring